### ISSUE TITLE
Facing java.lang.NoClassDefFoundError: com/google/cloud/vertexai/VertexAI$Builder error when switch to Spring AI version -1.0.0-SNAPSHOT

### ISSUE THREAD

**Issue by amit-4-kumar** [spring-projects/spring-ai#1283]
Facing below run time issue when updated spring AI version from 0.8.1-SNAPSHOT  to 1.0.0-SNAPSHOT version. Earlier this was not issue but now facing this issue.

Error msg -
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.google.cloud.vertexai.VertexAI]: Factory method 'vertexAi' threw exception with message: com/google/cloud/vertexai/VertexAI$Builder
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:177)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:644)
	... 19 common frames omitted
Caused by: java.lang.NoClassDefFoundError: com/google/cloud/vertexai/VertexAI$Builder
	at org.springframework.ai.autoconfigure.vertexai.gemini.VertexAiGeminiAutoConfiguration.vertexAi(VertexAiGeminiAutoConfiguration.java:57)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:140)
	... 20 common frames omitted
Caused by: java.lang.ClassNotFoundException: com.google.cloud.vertexai.VertexAI$Builder
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 26 common frames omitted

**Comment by markpollack** [comment]
Our integration tests for M2 passed with vertex.  what are you doing specifically?

**Comment by csterwa** [comment]
If this is not already resolved, please open up with any specific issues you are seeing.
